server:
  port: 8724
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: prefixpath_route
          uri: lb://provider #此处需要使用lb协议
          predicates:
            - Method=GET
          filters:
            - PrefixPath=/user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka/, http://localhost:8702/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
