server:
  port: 8724
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: prefixpath_route
          uri: lb://consul-provider #此处需要使用lb协议
          predicates:
            - Method=GET
          filters:
            - PrefixPath=/user

logging:
  level:
    org.springframework.cloud.gateway: debug
