server:
  port: 8710

spring:
  application:
    name: zuul

eureka:
  client:
    # 开启健康检查
    healthcheck:
      enabled: true
    service-url:
      # Eureka 注册中心的地址，多个地址有逗号隔开
      defaultZone: http://localhost:8701/eureka,http://localhost:8702/eureka
  instance:
    # eureka client发送心跳给server端的频率, 如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance
    lease-renewal-interval-in-seconds: 3
    # eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 6

#路由规则定义: 这里定义两种路由规则route1和route2，代表访问网关/test1/**或/test2/**时，
#路由到服务名为 eureka-service1 或 eureka-service2中的服务集群去。
zuul:
  routes:
    provider:
      path: /provider/**
    comsumer:
      path: /comsumer/**
  prefix: /api

management:
  endpoints:
    web:
      exposure:
        include: 'routes'
