server:
  port: 8723 # 服务提供方

# 指定当前eureka客户端的注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka,http://localhost:8702/eureka
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6

#当前服务名称
spring:
  application:
    name: eureka-service2