# 应用名称
spring:
  # 集群情况下，请保证application.name 相同，否则不可用（在eureka控制台unavailable-replicas中可以看到不可用的集群节点）
  application:
    name: eureka-server

---
server:
  port: 8701

spring:
  profiles: server1

eureka:
  instance:
    #hostname需要和自己域名保持一致
    hostname: server1
  client:
    # 是否将自己注册到注册中心
    register-with-eureka: true
    # 是否从注册中心检索服务（获取注册信息）
    fetch-registry: true
    service-url:
      #Eureka 注册中心的地址，多个地址有逗号隔开
      defaultZone: http://server2:8702/eureka
  server:
    # 是否开启自我保护模式，默认为true
    enable-self-preservation: true
    # eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 3000

---
server:
  port: 8702
spring:
  profiles: server2

eureka:
  instance:
    #hostname需要和自己域名保持一致
    hostname: server2
  client:
    # 是否将自己注册到注册中心
    register-with-eureka: true
    #是否从注册中心检索服务（获取注册信息）
    fetch-registry: true
    service-url:
      #Eureka 注册中心的地址，多个地址有逗号隔开
      defaultZone: http://server1:8701/eureka















