server:
  port: 8721
spring:
  application:
    name: consul-consumer
  cloud:
    consul: #Consul服务注册发现配置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

feign:
  hystrix:
    enabled: true
